server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/o1egnazarov/config-repo.git
          clone-on-start: true
          default-label: main
          username: ${GIT_USER:noleg867@gmail.com}
          password: ${GIT_PASSWORD:levzarzver}

logging:
  level:
    org.springframework.cloud.config.server.git: DEBUG